# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-01 14:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterAPIKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A name for the API key that allows you to distinguish it from other API keys.', max_length=255)),
                ('key', models.CharField(max_length=255)),
                ('secret', models.CharField(max_length=255)),
                ('access_token', models.CharField(max_length=255)),
                ('access_token_secret', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TwitterConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_text', models.CharField(default='New game: http://{domain:s}{absolute_url:s}', max_length=255)),
                ('tweet_text_with_topic', models.CharField(default='New game: http://{domain:s}{absolute_url:s} (Topic: {topic:s})', max_length=255)),
                ('api_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bingo_tweets.TwitterAPIKey')),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
            ],
        ),
    ]
